### PR TITLE
Feature/sponsors component [OC-108]

### PR DESCRIPTION
**Pull request by samanehsan**
Add sponsors component to meeting landing page: 

screen shot 2017-07-25 at 10 40 20 am

### CODE REVIEW

**Comment by cameronblandford** [comment]
Beautiful! I don't know if there's a better way to do it or not, but the tier titles look sorta imbalanced to me. What are your thoughts?

**Comment by samanehsan** [comment]
Thank you! What do you mean by imbalanced?

**Comment by cameronblandford** [comment]
Resolved, good as is :+1:

**Comment by cameronblandford** [comment]
LGRTM!

**Pull request merged**
